language: minimal
os: linux
dist: bionic

python:
    - 3.8
    - pypy3

branches:
    only:
    - master

addons:
    apt:
        update: true
        packages:
            - ansible
            - fdfind

env:
    - ROOT_PATH=$TRAVIS_BUILD_DIR

install:
    - scripts/install.sh

before_script: 
    # linting phase
    - scripts/yamllint.sh
    - scripts/ansible_lint.sh

deploy:
    #