language: minimal
os: linux
dist: bionic

python:
    - 3.8
    - pypy3

branches:
    only:
    - master
env:
    global:
        - ROOT_PATH=$TRAVIS_BUILD_DIR
        - ANSIBLE_PYTHON_INTERPRETER=$( which python3 )


install:
    - scripts/install.sh

before_script: 
    # linting phase
    - scripts/yamllint.sh
    - scripts/ansible_lint.sh

deploy:
    #