language: minimal
os: linux
dist: bionic
python:
- 3.7
- pypy3
branches:
  only:
  - master
env:
  global:
  - ROOT_PATH=$TRAVIS_BUILD_DIR
  - ANSIBLE_VERSION='2.9.7*'
  - "$( which python3 )"

before_install:
- openssl aes-256-cbc -K $encrypted_0c6a0d3db87a_key -iv $encrypted_0c6a0d3db87a_iv -in ansible_controller.pem.enc -out ansible_controller.pem -d
- openssl aes-256-cbc -K $encrypted_4a18f61c0b67_key -iv $encrypted_4a18f61c0b67_iv -in docker_nodes.pem.enc -out docker_nodes.pem -d
- mv ansible_controller.pem "$ROOT_PATH/aws/ansible/files/ssh_keys/"
- mv docker_nodes.pem "$ROOT_PATH/ansible_controller/ansible/files/ssh_keys/"


install:
- ci/scripts/install_dependencies.sh
before_script:
- ci/scripts/yamllint.sh
- ci/scripts/ansible_lint.sh
deploy:
  - provider: script
    script:
      - aws/scripts/deploy_network.sh
      - aws/scripts/deploy_ec2.sh
      - aws/scripts/configure_ansible_controller.sh
      - aws/scripts/launch_docker_configuration.sh
