language: minimal

os: linux
dist: bionic

python:
  - 3.8
  - pypy3

branches:
  only:
    - master

env:
  global:
    - ROOT_PATH=$TRAVIS_BUILD_DIR

before_install:
  - openssl aes-256-cbc -K $encrypted_e4a7e545200e_key -iv $encrypted_e4a7e545200e_iv
    -in aws_udacity_lab_linux.pem.enc -out aws_udacity_lab_linux.pem -d
  - openssl aes-256-cbc -K $encrypted_8cbb94ebeb98_key -iv $encrypted_8cbb94ebeb98_iv
    -in manage_private_subnet_instance.pem.enc -out manage_private_subnet_instance.pem
    -d

install:
  - scripts/ubuntu_install.sh

before_script:
  - scripts/yamllint.sh
  - scripts/ansible_lint.sh