language: minimal
os: linux
dist: bionic
python:
- 3.7
- pypy3
branches:
  only:
  - master
env:
  global:
  - ROOT_PATH=$TRAVIS_BUILD_DIR
  - ANSIBLE_VERSION='2.9*'
  - DOCKER_PATH=ansible_controller/ansible/files/ssh_keys
  - ANSIBLE_PATH=aws/ansible/files/ssh_keys
  - PYTHON_INTERPRETER=$( which python3 )

before_install:
# https://github.com/travis-ci/travis.rb/issues/555
- openssl aes-256-cbc -d -K $DOCKER_KEY -iv $DOCKER_IV -in $DOCKER_PATH/docker_nodes.pem.enc -out $DOCKER_PATH/docker_nodes.pem
- openssl aes-256-cbc -d -K $ANSIBLE_KEY -iv $ANSIBLE_IV -in $ANSIBLE_PATH/ansible_controller.pem.enc -out $ANSIBLE_PATH/ansible_controller.pem
- echo "PYTHON_INTERPRETER $PYTHON_INTERPRETER"

install:
- ci/scripts/install_dependencies.sh
before_script:
- ci/scripts/yamllint.sh
- ci/scripts/ansible_lint.sh
deploy:
  - provider: script
    script:
      - aws/scripts/deploy_network.sh
      - aws/scripts/deploy_ec2.sh
      - aws/scripts/configure_ansible_controller.sh
      - aws/scripts/launch_docker_configuration.sh
