- hosts: docker_swarm_manager
  name: "Configure docker engine on docker manager"
  vars:
      root_path: '~'
      ca_private_key_name: 'CA-private.pem'
      server_private_key_name: 'docker-manager-private.pem'
      server_certificate_name: 'docker-manager-certificate.pem'
      epel_dest: '/tmp/epel.rpm'
      epel_release_url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      skip_docker_py: true
      skip_docker_compose: true
      skip_docker_swarm: true

      docker_service_override: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd --tlsverify \
              --tlscacert=/root/CA-certificate.pem \
              --tlscert=/root/docker-manager-certificate.pem \
              --tlskey=/root/docker-manager-private.pem \
              -H fd:// -H tcp://0.0.0.0:2376

  pre_tasks:
      - name: "Download epel package"
        get_url:
            url: "{{ epel_release_url }}"
            dest: "{{ epel_dest }}"

      - name: "Install epel"
        become: true
        yum:
            state: present
            update_cache: true
            name:
                - "{{ epel_dest }}"

      - name: "Install dependencies"
        become: true
        yum:
            state: present
            update_cache: true
            name:
                - 'python-pip'

      - name: "Install pip dep"
        become: true
        pip:
            name: cryptography
            state: present
            version: 2.9.2
            extra_args: --upgrade

  roles:
      - role: docker_hardening
        become: true
      - role: atosatto.docker-swarm
        become: true
