---
- name: "Deploy VPC in AWS"
  hosts: localhost

  pre_tasks:
      - name: "Python & Pip version"
        shell: |
          python --version
          pip freeze
        register: SEQOUT
        changed_when: false

      - name: "Python & Pip version output"
        debug:
            msg: "{{ SEQOUT.stdout_lines }}"
        changed_when: false

  roles:
      - aws_network_deploy
