plugin: aws_ec2
regions:
    - us-east-1

filters:
    tag:Name: Docker*
    key-name: aws_udacity_lab_linux
    instance-state-name: running

groups:
    docker_swarm_manager: "'Manager' in (tags.DockerType)"
    docker_swarm_worker: "'Worker' in (tags.DockerType)"
    docker_engine: "'DockerType' in (tags)"

compose:
    ansible_user: "'centos'"
    ansible_host: private_ip_address
