# Configure the local system in order to run the linting and test steps.
---

- hosts: 127.0.0.1
  connection: local
  name: "Configure building environment"
  gather_facts: false
  vars_files: "vars/configure_building_environment.yml"

  tasks:
    - name: Install virtualenv
      become: true
      apt:
        name: virtualenv
        state: present
        update_cache: true
        allow_unauthenticated: true

    - name: Install fd package
      become: true
      apt:
        state: present
        deb: "{{ fd_download_path }}"

    - name: Copy requirements
      copy:
        src: requirements.txt
        dest: "{{ virtual_env_path }}"

    - name: Create virtual environment"
      become: false
      pip:
        virtualenv: "{{ virtual_env_path }}"
        state: present
        requirements: "{{ virtual_env_path }}/requirements.txt"
