# CentOs instance
---
- hosts: all
  name: "Configure ansible controller"
  vars_files: "vars/configure_ansible_controller.yml"
  vars:
    epel_dest: '/tmp/epel.rpm'
    project_root_dir: "{{ lookup('env', 'ROOT_PATH') }}"

  tasks:
    - name: "Test ROOT PATH env variable"
      debug:
        msg: "ROOT PATH {{ project_root_dir }}"

    - name: "Download epel package"
      get_url:
        url: "{{ epel_release_url }}"
        dest: "{{ epel_dest }}"

    - name: "Install epel"
      become: true
      yum:
        state: present
        update_cache: true
        name:
          - "{{ epel_dest }}"

    - name: "Install ansible & git"
      become: true
      yum:
        state: present
        update_cache: true
        name:
          - 'ansible'
          - 'git'

    - name: "Copy private ssh key"
      copy:
        src: "{{ project_root_dir }}/ansible/files/ssh_keys/manage_private_subnet_instance.pem"
        dest: '~/.ssh/'
        mode: '0400'

    - name: "Clone git"
      git:
        repo: 'https://github.com/giovannibaratta/Code-challenge.git'
        dest: "~/Code-Challenge/"
        version: "master"
        clone: true
